// Power Broker v1.4
#include <iostream>
#include <vector>
#include <string>
#include <cstdlib>
#include <ctime>
#include <algorithm>
#include <fstream>
using namespace std;
enum class Difficulty { EASY = 0, NORMAL = 1, HARD = 2 };
struct DiffConfig { int initialCash; int initialPower; int dayLimit; int volatility; double aiAggression; };
vector<DiffConfig> DIFFS = { {150000,150,30,8,0.3},{100000,100,30,12,0.6},{60000,80,25,18,0.9} };
struct Event { string name, desc; int priceImpact; bool isBoss; };
vector<Event> NEVT = { {"AI芯片禁令","美国扩大芯片出口管制",+40,false},{"数据中心故障","某大厂数据中心宕机",+25,false},{"新能源突破","电价暴跌，算力成本降低",-20,false},{"新矿难","内蒙古矿难，GPU供应紧张",+30,false},{"大厂抛售","某巨头出售过剩算力",-35,false},{"政策利好","国家出台AI算力扶持政策",+15,false},{"黑客攻击","交易所遭攻击",-15,false},{"5nm量产","新一代制程量产，成本下降",-25,false},{"算力泡沫","市场过热，监管介入",-20,false},{"战争风险","地缘冲突升级",+35,false},{"矿场事故","西部矿场安全事故",+20,false},{"关税下调","进口GPU关税降低",-18,false} };
vector<Event> BEVT = { {"量子计算突破","量子计算机商用量产，算力格局重塑！",+80,true},{"AI觉醒事件","AI自我意识觉醒，引发市场恐慌！",+70,true},{"算力战争爆发","全球算力军备竞赛，价格暴涨！",+90,true},{"算力寒冬","全球经济衰退，AI投资暴跌！",-75,true},{"核爆级漏洞","重大安全漏洞，所有算力停摆！",-60,true},{"算力之王诞生","统一AI算力联盟成立，价格锁定！",+50,true} };
enum class Ach { FIRST, BULK, P10K, P100K, LOSS, STR3, STR5, PWR1K, ALLIN, BOSS, DEAL, HARD };
struct Achievement { Ach type; string name, desc; bool unlocked; Achievement(Ach t, const string& n, const string& d): type(t), name(n), desc(d), unlocked(false) {} };
vector<Achievement> ACHS = { {Ach::FIRST,"初入市场","完成首次交易"},{Ach::BULK,"大额交易","单次买卖50单位"},{Ach::P10K,"小有盈利","累计盈利10000美元"},{Ach::P100K,"百万富翁","累计盈利100000美元"},{Ach::LOSS,"触底反弹","资产缩水50%后恢复"},{Ach::STR3,"三连胜","连续3天赚钱"},{Ach::STR5,"五连胜","连续5天赚钱"},{Ach::PWR1K,"算力大亨","持有1000单位算力"},{Ach::ALLIN,"孤注一掷","全仓买入"},{Ach::BOSS,"Boss克星","成功应对Boss级事件"},{Ach::DEAL,"算力交易王","总交易量1000单位"},{Ach::HARD,"硬核玩家","通关Hard难度"} };
struct Competitor { string name; int cash, power, price; Competitor(const string& n, int c, int p, int pr): name(n), cash(c), power(p), price(pr) {} };
vector<Competitor> mkComps(Difficulty d) { vector<Competitor> c; c.emplace_back("算力精灵(AI)",80000,80,100); c.emplace_back("芯片大亨(AI)",60000,60,100); if(d!=Difficulty::EASY) c.emplace_back("量子猎手(AI)",50000,40,100); return c; }
struct GameState { Difficulty diff; int day, cash, power, price, profit, volume; int initAssets; int winStreak; bool bossToday; unordered_map<Ach,bool> ach; GameState(): day(1),cash(100000),power(100),price(100),profit(0),volume(0),initAssets(0),winStreak(0),bossToday(false) { for(auto& a: ACHS) ach[a.type]=false; } };
class TS { public: static bool buy(GameState& s, int a, int p) { int c=a*p; if(c>s.cash) return false; s.cash-=c; s.power+=a; s.volume+=a; return true; } static bool sell(GameState& s, int a, int p) { if(a>s.power) return false; s.cash+=a*p; s.power-=a; s.volume+=a; return true; } static int assets(const GameState& s, int p) { return s.cash+s.power*p; } };
class ME { int vol; public: ME(int v): vol(v) { srand(time(NULL)+clock()%1000); } int fluc() { return (rand()%(vol*2+1))-vol; } Event ne() { return NEVT[rand()%NEVT.size()]; } Event be() { return BEVT[rand()%BEVT.size()]; } int upd(int p, Event* e) { int c=fluc(); if(e) c+=(p*e->priceImpact)/100; return max(20,min(500,p+c)); } };
class AI { double agr; public: AI(double a): agr(a) {} void tick(Competitor& c, int mp) { int a=rand()%100; if(mp>c.price*1.1) { if(a<agr*60&&c.power>10) { int sa=min(c.power,5+rand()%20); c.cash+=sa*mp; c.power-=sa; } } else if(mp<c.price*0.9) { if(a<agr*60) { int ba=min(c.cash/mp,5+rand()%20); if(ba>0) { c.cash-=ba*mp; c.power+=ba; } } } c.price=mp; } };
class ASys { static void unlock(GameState& s, Ach t) { for(auto& a: ACHS) if(a.type==t&&!a.unlocked) { a.unlocked=true; s.ach[t]=true; cout<<endl<<"  [成就解锁] "<<a.name<<" - "<<a.desc<<endl; } } public: static void onFirst(GameState& s) { unlock(s,Ach::FIRST); } static void onBulk(GameState& s,int amt) { if(amt>=50) unlock(s,Ach::BULK); } static void onProfit(GameState& s,int p) { if(p>=10000) unlock(s,Ach::P10K); if(p>=100000) unlock(s,Ach::P100K); } static void onStreak(GameState& s,int w) { if(w>=3) unlock(s,Ach::STR3); if(w>=5) unlock(s,Ach::STR5); } static void onPower(GameState& s,int p) { if(p>=1000) unlock(s,Ach::PWR1K); } static void onAllIn(GameState& s) { unlock(s,Ach::ALLIN); } static void onBoss(GameState& s) { unlock(s,Ach::BOSS); } static void onVolume(GameState& s,int v) { if(v>=1000) unlock(s,Ach::DEAL); } static void onHard(GameState& s) { if(s.diff==Difficulty::HARD) unlock(s,Ach::HARD); } static void onLoss(GameState& s) { unlock(s,Ach::LOSS); } static void list(const GameState& s) { cout<<endl<<"  ===== 成就列表 ====="<<endl; int n=0; for(auto& a: ACHS) { string mk=s.ach.at(a.type)?"[*]":"[ ]"; cout<<"  "<<mk<<" "<<a.name<<" - "<<a.desc<<endl; if(s.ach.at(a.type)) n++; } cout<<"  已解锁: "<<n<<"/"<<ACHS.size()<<endl; } };
class SL { public: static bool save(const GameState& s, const string& f="save.pb") { ofstream of(f); if(!of) return false; of<<s.day<<endl<<s.cash<<endl<<s.power<<endl<<s.price<<endl<<s.profit<<endl<<s.volume<<endl<<s.winStreak<<endl<<s.initAssets<<endl<<(s.bossToday?1:0)<<endl; for(auto& a: ACHS) of<<(s.ach.at(a.type)?1:0)<<endl; of<<(int)s.diff<<endl; of.close(); return true; } static bool load(GameState& s, const string& f="save.pb") { ifstream ifs(f); if(!ifs) return false; string ln; auto ri=[&](int& v){getline(ifs,ln);v=stoi(ln);}; auto rb=[&](bool& v){getline(ifs,ln);v=(ln=="1");}; ri(s.day);ri(s.cash);ri(s.power);ri(s.price);ri(s.profit);ri(s.volume);ri(s.winStreak);ri(s.initAssets);rb(s.bossToday); for(auto& a: ACHS){int v;ri(v);s.ach.at(a.type)=(v==1);a.unlocked=(v==1);} int d;ri(d);s.diff=(Difficulty)d; ifs.close(); return true; } };
class UI { public: static void clear() { cout<<"\\033[2J\\033[H"; } static void hdr(int d) { cout<<"=========================================="<<endl<<"    算力经纪人 v1.4 | Power Broker   Day "<<d<<endl<<"=========================================="<<endl; } static void status(const GameState& s, int pr, const vector<Competitor>& cs) { cout<<"  资金: $"<<s.cash<<endl<<"  算力: "<<s.power<<" 单位"<<endl<<"  市价: $"<<pr<<"/单位"<<endl<<"  总资产: $"<<TS::assets(s,pr)<<endl<<"  累计盈利: $"<<s.profit<<endl<<"  --- 竞争对手 ---"<<endl; for(auto& c: cs) cout<<"  ["<<c.name<<"] 现金:$"<<c.cash<<" 算力:"<<c.power<<"单位"<<endl; }
static void event(const Event& e) { if(e.isBoss) cout<<endl<<"  *** BOSS级事件 ***"<<endl; cout<<"  [事件] "<<e.name<<endl<<"        "<<e.desc<<endl; if(e.isBoss) cout<<"        冲击巨大！影响: "<<e.priceImpact<<"%"<<endl; }
static void menu() { cout<<endl<<"  操作:"<<endl<<"    [1]买入10 [2]买入50 [3]自定义买入"<<endl<<"    [4]卖出10 [5]卖出50 [6]自定义卖出"<<endl<<"    [7]存档 [8]读档 [9]成就 [q]退出"<<endl; }
static void end(const GameState& s) { cout<<"=========================================="<<endl<<"           游戏结束 - Game Over"<<endl<<"=========================================="<<endl<<"最终总资产: $"<<TS::assets(s,s.price)<<endl<<"总利润: $"<<s.profit<<endl<<"最终持有算力: "<<s.power<<" 单位"<<endl; int st=0; if(s.profit>0) st++; if(s.profit>=50000) st++; if(s.profit>=100000) st++; if(s.diff==Difficulty::HARD) st++; cout<<"  评价: "; for(int i=0;i<st;i++) cout<<"*"; for(int i=st;i<5;i++) cout<<"-"; cout<<endl<<"=========================================="<<endl; }
static void bossWarn(int d) { cout<<endl<<"  *** BOSS警告：第"<<d<<"天将有大事发生！ ***"<<endl; } static int diffMenu() { cout<<endl<<"  难度选择："<<endl<<"    [1] 简单 (Easy)    - 初始资金150000美元"<<endl<<"    [2] 普通 (Normal) - 初始资金100000美元"<<endl<<"    [3] 困难 (Hard)   - 初始资金60000美元"<<endl<<"    > "; int c;cin>>c;cin.ignore(); return (c>=1&&c<=3)?c-1:1; } static void aiAct(const string& n, const string& a) { cout<<"  [AI] "<<n<<": "<<a<<endl; } };
class Game { GameState st; ME* mkt; vector<Competitor> comps; bool firstDone=false, allInDone=false, lossFlag=false; void init(Difficulty d) { const DiffConfig& c=DIFFS[(int)d]; st.diff=d; st.cash=c.initialCash; st.initAssets=c.initialCash+c.initialPower*100; st.power=c.initialPower; mkt=new ME(c.volatility); comps=mkComps(d); } void aiTurn(Competitor& c) { AI ai(DIFFS[(int)st.diff].aiAggression); ai.tick(c,st.price); const char* as[]={"按兵不动","小量交易","观望中...","调整仓位","追涨杀跌"}; UI::aiAct(c.name,as[rand()%5]); } void checkAch() { int a=TS::assets(st,st.price); int p=a-st.initAssets; st.profit=p; if(st.volume>0&&!firstDone) { ASys::onFirst(st); firstDone=true; } ASys::onProfit(st,p); ASys::onStreak(st,st.winStreak); ASys::onPower(st,st.power); ASys::onVolume(st,st.volume); if(!lossFlag&&a<=st.initAssets/2) lossFlag=true; if(lossFlag&&a>=st.initAssets) { ASys::onLoss(st); lossFlag=false; } }
bool trade(char ch) { int amt=0; bool ok=false; switch(ch) { case 1: ok=TS::buy(st,10,st.price);amt=10; break; case 2: ok=TS::buy(st,50,st.price);amt=50; break; case 4: ok=TS::sell(st,10,st.price);amt=10; break; case 5: ok=TS::sell(st,50,st.price);amt=50; break; case 3: { cout<<"  买入数量: ";int n;cin>>n;cin.ignore();ok=TS::buy(st,n,st.price);amt=n; break; } case 6: { cout<<"  卖出数量: ";int n;cin>>n;cin.ignore();ok=TS::sell(st,n,st.price);amt=n; break; } } if(ok) { cout<<"  操作成功"<<endl; ASys::onBulk(st,amt); if(!allInDone&&st.cash<st.price) { ASys::onAllIn(st); allInDone=true; } } else if(ch>=1&&ch<=6) cout<<"  操作失败（资金或算力不足）"<<endl; return ok; } void endDay() { int a=TS::assets(st,st.price); int p=a-st.initAssets; st.profit=p; if(p>0) st.winStreak++; else st.winStreak=0; checkAch(); if(st.bossToday) ASys::onBoss(st); }
public: Game(): mkt(nullptr) { for(auto& a: ACHS) a.unlocked=false; } ~Game() { delete mkt; } void run() { string cmd; UI::clear(); cout<<"========================================"<<endl<<"   算力经纪人 | Power Broker v1.4"<<endl<<"   成为AI算力市场的幕后操盘手"<<endl<<"========================================"<<endl<<"  [1] 新游戏  [2] 继续存档  [q] 退出"<<endl<<"> "; if(!(cin>>cmd)) return; cin.ignore(); if(cmd=="2") { if(SL::load(st)) { delete mkt; mkt=new ME(DIFFS[(int)st.diff].volatility); comps=mkComps(st.diff); for(auto& a: ACHS) a.unlocked=st.ach[a.type]; cout<<"  存档读取成功！当前Day "<<st.day<<endl; } else cout<<"  无存档，从新游戏开始..."<<endl; } else if(cmd=="q") return; else { int di=UI::diffMenu(); init((Difficulty)di); } cout<<"  按回车开始..."<<endl; getline(cin,cmd);
while(st.day<=DIFFS[(int)st.diff].dayLimit) { UI::clear(); UI::hdr(st.day); if(st.day==10||st.day==20) UI::bossWarn(st.day); UI::status(st,st.price,comps); Event e = (st.day==10||st.day==20)?mkt->be():mkt->ne(); st.bossToday=(st.day==10||st.day==20); st.price=mkt->upd(st.price,&e); UI::event(e); for(auto& c: comps) aiTurn(c); UI::menu(); cout<<"> "; cout.flush(); if(!getline(cin,cmd)) break; if(cmd.empty()) continue; char ch=cmd[0]; if(ch==113||ch==81) break;
else if(ch==55) { if(SL::save(st)) cout<<"  存档成功！"<<endl; else cout<<"  存档失败！"<<endl; cout<<"  按回车继续..."<<endl; getline(cin,cmd); continue; } else if(ch==56) { GameState ld; if(SL::load(ld)) { st=ld; delete mkt; mkt=new ME(DIFFS[(int)st.diff].volatility); comps=mkComps(st.diff); for(auto& a: ACHS) a.unlocked=st.ach[a.type]; cout<<"  读档成功！当前Day "<<st.day<<endl; } else cout<<"  读档失败！"<<endl; cout<<"  按回车继续..."<<endl; getline(cin,cmd); continue; } else if(ch==57) { ASys::list(st); cout<<"  按回车返回..."<<endl; getline(cin,cmd); continue; } else { trade(ch); cout<<"  按回车继续..."<<endl; getline(cin,cmd); } endDay(); st.day++; } ASys::onHard(st); UI::clear(); UI::end(st); ASys::list(st); cout<<endl<<"  按回车退出..."<<endl; getline(cin,cmd); } };

int main(){Game g;g.run();return 0;}
